Document: bloonix-plugins-memcached
Title: Debian bloonix-plugins-memcached Manual
Author: <insert document author here>
Abstract: This manual describes what bloonix-plugins-memcached is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bloonix-plugins-memcached/bloonix-plugins-memcached.sgml.gz

Format: postscript
Files: /usr/share/doc/bloonix-plugins-memcached/bloonix-plugins-memcached.ps.gz

Format: text
Files: /usr/share/doc/bloonix-plugins-memcached/bloonix-plugins-memcached.text.gz

Format: HTML
Index: /usr/share/doc/bloonix-plugins-memcached/html/index.html
Files: /usr/share/doc/bloonix-plugins-memcached/html/*.html
